# Generated by Django 5.2.17 on 2026-09-11 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='URL identifier, e.g. sql-injections', unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LabSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Paragraphs. Separate paragraphs with a blank line.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='labs/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.lab')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
