# Generated by Django 5.2.17 on 2026-09-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_lab_labsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='contact_image',
            field=models.ImageField(blank=True, help_text='Image displayed beside the contact form.', null=True, upload_to='contact/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contact_image_alt',
            field=models.CharField(blank=True, default='Security operations workspace', max_length=200),
        ),
    ]
