# Generated by Django 5.2.17 on 2026-09-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_siteconfig_contact_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writeup',
            options={'ordering': ['event', 'category', 'order', 'task']},
        ),
        migrations.AddField(
            model_name='writeup',
            name='category',
            field=models.CharField(choices=[('Web Exploitation', 'Web Exploitation'), ('Cryptography', 'Cryptography'), ('Forensics', 'Forensics'), ('Binary Exploitation', 'Binary Exploitation'), ('Reverse Engineering', 'Reverse Engineering'), ('General Skills', 'General Skills'), ('OSINT', 'OSINT'), ('Steganography', 'Steganography'), ('Networking', 'Networking'), ('Privilege Escalation', 'Privilege Escalation'), ('Misc', 'Misc')], default='Misc', max_length=60),
        ),
        migrations.AddField(
            model_name='writeup',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='certification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coursetext',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='experiencepoint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='labsection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='writeup',
            name='event',
            field=models.CharField(help_text='e.g. PicoCTF, HackTheBox, TryHackMe', max_length=120),
        ),
        migrations.AlterField(
            model_name='writeup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='writeup',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of tag strings, e.g. ["rsa", "python"]'),
        ),
    ]
