# Generated by Django 5.2.17 on 2026-09-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_writeup_options_writeup_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writeup',
            options={'ordering': ['event', 'order', 'task']},
        ),
        migrations.RemoveField(
            model_name='writeup',
            name='category',
        ),
        migrations.RemoveField(
            model_name='writeup',
            name='difficulty',
        ),
        migrations.AlterField(
            model_name='writeup',
            name='event',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='writeup',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='JSON list, e.g. ["Cryptography", "rsa"]. Include a category name as a tag to file it into that folder.'),
        ),
    ]
