# Generated by Django 5.2.17 on 2026-09-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_writeup_options_remove_writeup_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='group',
            field=models.CharField(default='OWASP Juice Shop', help_text='Project name that groups related labs, e.g. OWASP Juice Shop', max_length=200),
        ),
        migrations.AlterField(
            model_name='lab',
            name='slug',
            field=models.SlugField(help_text='URL identifier, e.g. injection', unique=True),
        ),
    ]
