# Generated by Django 5.2.17 on 2026-09-15 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_lab_group_alter_lab_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='sections',
        ),
        migrations.CreateModel(
            name='LessonSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True, help_text='Separate paragraphs with a blank line.')),
                ('bullets', models.TextField(blank=True, help_text='Write each bullet point on a new line.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.lesson')),
            ],
            options={
                'verbose_name': 'Lesson Section',
                'verbose_name_plural': 'Lesson Sections',
                'ordering': ['order'],
            },
        ),
    ]
