# Generated by Django 5.2.17 on 2026-09-15 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_lesson_sections_lessonsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='Write this lesson using Markdown. Use ## for headings, - for bullet points, and ![image description](image-url) for images.'),
        ),
        migrations.CreateModel(
            name='LessonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lessons/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption or image description.', max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.lesson')),
            ],
            options={
                'verbose_name': 'Lesson Image',
                'verbose_name_plural': 'Lesson Images',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='LessonSection',
        ),
    ]
